### ISSUE TITLE
README is way too long

### ISSUE THREAD

**Issue by McSinyx** [vicious-widgets/vicious#100]
The current README include the reference to every officially supported widget type, which makes it rather difficult to navigate without proper indexing.  I'm thinking about migrating it to separate pages, probably in [Sphinx](https://www.sphinx-doc.org).  This will also make the contrib widget types more discoverable.

**Comment by Mic92** [comment]
Might be also worth considering moving it to the wiki. In my experience this lowers entry barrier for writing documentation i.e. [direnv](https://github.com/direnv/direnv/wiki)

**Comment by mutlusun** [comment]
Hello,
I have created an example wiki using the github wiki. You want to have a look? But I'm okay to create it with sphinx as well!

**Comment by McSinyx** [comment]
I'm sorry for procrastinating on something I said to work on for quite long :sweat_smile:

@mutlusun, thank you for the wiki prototype.  Also to @Mic92, I think we have 2 separate concerns here:
1. Documentation contribution entry barrier: Using GitHub Wiki w/o permission would best facilitate this
2. Indexing: we'd need to use something else (like Sphinx or some external wiki) since GitHub Wiki does not preserve page order

Regarding the first point, per my observation there has not been a lot of interactions on Vicious lately.  For one thing it's 2020, but I also think it's because awesome popularity (or at least its new adoption rate) has been decreasing since the raise of Wayland.  If we decide to not use a wiki to host our docs, all what others need to do to fix something would be filing an issue (in case perse is not familiar with opening PR) and we'll edit manually.  To be completely fair, one need not even to register to edit wikis on the other hand.

As for Sphinx, the plus points I can think of are as follow:
* The docs will be part of the source tree (well we can [include GitHub wiki as a submodule](https://github.com/McSinyx/brutalmaze), but per my experience it's inconvenient to sync it) for offline look-up
* It's easy to build the docs locally if one doesn't like reading plain text as much
* We can use [Read the Docs](https://readthedocs.org/) to build upon push and even [pull requests](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html)

**Comment by mutlusun** [comment]
Thanks for your ideas!

I agree with you that Github wiki can be a bit messy sometimes without page ordering. My impression is also that the popularity of awesome is decreasing (though I don't see a real succesor on wayland basis). Actually, I don't use awesome anymore, too.

I like the idea to host the pages on Read the docs. I don't have any experience with sphinx so far. Just one note: Maybe it's easier to use [LuaDoc](https://keplerproject.github.io/luadoc/manual.html)? This way we can keep source and documentation in the same files. We probably don't need any documentation of single functions but of the modules. But I don't have any experience neither with LuaDoc nor with Sphinx ;-)

**Comment by McSinyx** [comment]
> Actually, I don't use awesome anymore, too.

:cry: It's a good thing that we did not drop support for non-awesome use though.

> Maybe it's easier to use LuaDoc? This way we can keep source and documentation in the same files.

IDK TBH.  There exists [a Sphinx extension that can integrate LuaDoc/LDoc](https://pypi.org/project/sphinx-lua/), so my main concern is how much I can automate the moving of documentations from README.  I'll consider your reply as a green flag and start porting the docs to Sphinx and we'll see what'll turn out to be the easy way.
