### ISSUE TITLE
vicious.widgets.gmail docs update

### ISSUE THREAD

**Issue by senyai** [vicious-widgets/vicious#105]
Hi!
Using [these](https://pythoncircle.com/post/727/accessing-gmail-inbox-using-python-imaplib-module/) instructions I was able to use `vicious.widgets.gmail` without disabling two step verification. Can someone update the docs?

**Comment by McSinyx** [comment]
Thanks for the information.  Unfortunately this feature is exclusive for google accounts with 2FA (which mine are not), so I'd like to defer this to others.  If you want to take up the work, [here is the official (?) instruction](https://support.google.com/accounts/answer/185833) and file you'll need to edit is `docs/source/widgets.rst`.

**Comment by senyai** [comment]
Let me clear something out. You can't create 'app password' on this page https://myaccount.google.com/security?gar=1, right?

**Comment by McSinyx** [comment]
TBH, I don't know since I can't test it myself.  From the docs:

> 1. Go to your Google Account.
> 2. Select Security.
> 3. Under "Signing in to Google," select App Passwords. You may need to sign in. If you don’t have this option, it might be because: [...]

Since you was able to do it, does the *Signing in to Google* tab hint anything about *App Passwords*?  Otherwise that needs to be noted.

**Comment by senyai** [comment]
This is my tab:
![image](https://user-images.githubusercontent.com/76137/96374159-b298b780-1179-11eb-859b-725ba948c921.png)
It showed "0 password" before I added one. I use physical key to access my account, so I'm not sure everyone has that section. Google authentication is confusing.

**Comment by McSinyx** [comment]
Thanks!  I updated my review comment.
