### ISSUE TITLE
Caching a wtype doesn't cache the values returned by widget type.

### ISSUE THREAD

**Issue by BeniaminK** [vicious-widgets/vicious#51]
When I cache the widget, and use different return values of it, I keep receiving the same response all the time.
In the following example, the widget in point 2. is being updated first, so the rest of the widgets using the same widget type will all the time receive the same response (not "$1", but "<span color='#00ff00''>⛁ </span>$3MB")

1. 
```
vicious.cache(vicious.widgets.mem)
```

2. 
```
memtotal = wibox.widget.textbox()

vicious.register(memtot, vicious.widgets.mem, "<span color='#00ff00''>⛁ </span>$3MB", 2)
```

3. 
```
membar = wibox.widget {        
    forced_width = graphwidth, 
    forced_height = graphheight,    
    background_color = "#0000FF",
    color = "#00FF00",
    widget = wibox.widget.progressbar,
}

vicious.register(membar, vicious.widgets.mem, "$1", 3)
```

4. 
```
mempct = wibox.widget.textbox()
vicious.register(mempct, vicious.widgets.mem, "$1%", 5)
```

**Comment by BeniaminK** [comment]
Basically, the problem was with the incorrect caching order of the data:
Was:
1. Receive update order ot wtype `wtype` from widget X
2. Compute the updated values
3. Compute the formatted data for widget X
4. Store in cache the formatted data
5. Receive update order of wtype `wtype` from widget Y
6. Get data from cache (formatted data instead of the raw wtype return value)
7. Widget Y receives an ill-formatted data

I made a pull request fixing this error.
Mic92/vicious#52

**Comment by drot** [comment]
Yeah just noticed this issue too, the pull request fixes it.

**Comment by McSinyx** [comment]
Shouldn't this be closed now?
