### ISSUE TITLE
vicious.force has to be called twice to redraw widget immediately

### ISSUE THREAD

**Issue by Veratil** [vicious-widgets/vicious#57]
I've made a volume widget which I want to have redrawn immediately after pressing my volume keys, currently I have to call `vicious.force({myvolume})` twice in a row to redraw.

I've tested with cache enabled, without cache, with basic textbox widget, with advanced widget combinations. I always have to call force twice.

**Comment by mutlusun** [comment]
Hello,
thanks for your report. Unfortunately I cannot reproduce this problem on the latest master. I think, I don't have any cache enabled. @Mic92 Do you have any ideas?
Best

**Comment by McSinyx** [comment]
I can reproduce this bug. It seems to me that  `vicious.force` need to be called twiced after an automatic update in order to perform a force update (afterwards `force` works kind of as expected).

I don't see any relation of this bug to cache though.
