### ISSUE TITLE
New maintainer wanted.

### ISSUE THREAD

**Issue by Mic92** [vicious-widgets/vicious#60]
I no longer use awesome wm. Do you want to take over the project? @mutlusun

**Comment by Mic92** [comment]
@makefu are still using this?

**Comment by Mic92** [comment]
There is no much work to do. Awesome wm is stable and so is the APIs vicious gets its data from.

**Comment by makefu** [comment]
yep i still use awesomewm+vicious but only as a mere user.

**Comment by philsc** [comment]
Could you elaborate on what would be involved in being a maintainer? I very much like your library and would hate to see it abandoned.

Out of curiosity, what window manager did you switch to?

**Comment by Mic92** [comment]
Well basically a maintainer needs to look after new pull request and test if they work. Vicious is not in any package registry so one only needs to create a new release on github by uploading a tag if necessary. Some linux distributions have adopted my fork and will update on their own packages accordingly.

I switched to KDE for originally weird reasons. Initially I wanted to test my crash recording tool and remembered KDE to be pretty buggy. Then I released it was actually more stable and now I enjoy that I can setup bluetooth pairing without having to look into the manual. Guess this is part of growing up or so.

I can migrate this project to a github organisation and invite people that are interested in continuing the development.

**Comment by Mic92** [comment]
Not breaking the API will be something that many people will appreciate. Awesome wm has done this in the past and lost some users that way.

**Comment by blueyed** [comment]
I'd be happy to help out.

**Comment by drot** [comment]
Speaking of breakage, widget catching is currently broken on awesome v4 unless #52 is applied. This should be a priority for whoever takes over before making a new release.

**Comment by Mic92** [comment]
I guess I create an vicious github organisation and give access to those who want to maintain this in future?

**Comment by Mic92** [comment]
@blueyed you got an invite.

**Comment by mutlusun** [comment]
Hello all,
thanks for your invitation to the organisation!

I don't have any Linux computer running with awesome so it would be hard for me to test and maintain the whole project. But I'm still happy to take care of the FreeBSD specific part of it! And how you can see from my late reply, I don't have so much time to reply in an appropriate range of time.

Are there any news from @blueyed ?

@Mic92 Actually I can understand your motivation to switch to another desktop environment. At work I'm using Gnome and I'm really pleased with it (except of the tiling extension. It isn't that mature, I would like to be it.). Let's see how long I am using awesomewm on my own computer ...

**Comment by McSinyx** [comment]
I'm not a Lua expert but I'm willing to help, esp. on the widget I use and the documentation. Imma use awesome until X is fully deprecated - after 2 years now using mouse just feels weird.

**Comment by blueyed** [comment]
Thanks for the invite!
I am using vicious since a while as the base for some of my widgets, and just want to help out a bit as good as I can.  I am using Arch Linux myself.
Let's see how this goes, thanks for all the work being put into this already.

**Comment by blueyed** [comment]
Let's leave it to @Mic92 to close this, and maybe also invite others, e.g. @McSinyx.

**Comment by McSinyx** [comment]
> maybe also invite others, e.g. @McSinyx

Yes, please

**Comment by Mic92** [comment]
Invite sent.

**Comment by Mic92** [comment]
Seems like I switched back to awesome wm. Atleast until wayland gets stable enough to switch. Nevertheless having more maintainers is not a bad thing to have.

**Comment by kiike** [comment]
@Mic92 Hi Jörg! Could I be added as maintainer? I have been using Awesome+vicious daily for the last [10 years](https://github.com/kiike/dotfiles/tree/4525f43683d70bd68d80fad49d07b9cf2ad38928/awesome). I am relearning Lua since my use of it has been spotty at best, but I plan to add first-class support for OpenBSD in Vicious.

**Comment by blueyed** [comment]
@kiike 
Thanks for your interest!
I think you can already start with creating PRs and triaging issues etc, without being a collaborator (of course).

**Comment by kiike** [comment]
@blueyed sure! I've already submitted a couple PRs with one more on the queue ;).

**Comment by Mic92** [comment]
I sent an invite to @kiike

**Comment by kiike** [comment]
Thanks @Mic92!
