### ISSUE TITLE
[feature request] function to convert seconds into hour,minute,second in  mpd.lua widget

### ISSUE THREAD

**Issue by xhc1** [vicious-widgets/vicious#66]
could be very useful for mpd.lua widget, I added 2 more lines  as you can see:

    -- Mpd: provides Music Player Daemon information
    -- vicious.widgets.mpd
    local mpd = {}

    -- {{{ MPD widget type
    local function worker(format, warg)
    local mpd_state  = {
        ["{volume}"] = 0,
        ["{state}"]  = "N/A",
        ["{Artist}"] = "N/A",
        ["{Title}"]  = "N/A",
        ["{Album}"]  = "N/A",
        ["{Genre}"]  = "N/A",
        ["{time}"]  = "N/A",                                      <----- ADDED THIS LINE
        --["{Name}"] = "N/A",
        --["{file}"] = "N/A",
    }

    -- Fallback to MPD defaults
    local pass = warg and (warg.password or warg[1]) or "\"\""
    local host = warg and (warg.host or warg[2]) or "127.0.0.1"
    local port = warg and (warg.port or warg[3]) or "6600"

    -- Construct MPD client options
    local mpdh = "telnet://"..host..":"..port
    local echo = "echo 'password "..pass.."\nstatus\ncurrentsong\nclose'"

    -- Get data from MPD server
    local f = io.popen(echo.." | curl --connect-timeout 1 -fsm 3 "..mpdh)

    for line in f:lines() do
        for k, v in string.gmatch(line, "([%w]+):[%s](.*)$") do
            if     k == "volume" then mpd_state["{"..k.."}"] = v and tonumber(v)
            elseif k == "state"  then mpd_state["{"..k.."}"] = helpers.capitalize(v)
            elseif k == "Artist" then mpd_state["{"..k.."}"] = helpers.escape(v)
            elseif k == "Title"  then mpd_state["{"..k.."}"] = helpers.escape(v)
            elseif k == "Album"  then mpd_state["{"..k.."}"] = helpers.escape(v)
            elseif k == "Genre"  then mpd_state["{"..k.."}"] = helpers.escape(v)
            elseif k == "time"  then mpd_state["{"..k.."}"] = helpers.escape(v)   <-- AND THIS
            --elseif k == "Name" then mpd_state["{"..k.."}"] = helpers.escape(v)
            --elseif k == "file" then mpd_state["{"..k.."}"] = helpers.escape(v)
            end
        end
    end
    f:close()
 
    return mpd_state
    end
     -- }}}
 
    return setmetatable(mpd, { __call = function(_, ...) return worker(...) end })

this code allows to show time in mpd.widget in rc.lua  but in seconds, for example:

128:180    (which means track playing at 2:08 of 3:00
showing 2:08 / 3:00 or something like that would be more cool :)

**Comment by Mic92** [comment]
I use https://github.com/Mic92/utils/blob/master/wimpd.lua#L17 instead.

**Comment by xhc1** [comment]
thanks is it possible to implement timeformat function in vicious.helpers or mpd.lua or somewhere as default stuff?

**Comment by Mic92** [comment]
Does not lua already have functions for those? https://www.lua.org/pil/22.1.html

**Comment by McSinyx** [comment]
OK I'm gonna do it, if you are willing assist me on how to set mpd and a random client up and running for testing.

**Comment by xhc1** [comment]
Mic92 that is true I just talked about implementing that function into mpd widget for all users as default

**Comment by xhc1** [comment]
McSinyx I think problem is:   args["{time}"] doesnt return regular format of numbers (it is 128:300 as one) so that Mic92's function cant recognize it as number and args["{elapsed}"] returns seconds in format 128.493 for example, same for args["{duration}"]

**Comment by xhc1** [comment]
ok so function is here:

`function SecondsToClock(seconds)
     local seconds = tonumber(seconds)
   
     if seconds <= 0 then
       return "00:00:00";
     else
       hours = string.format("%02.f", math.floor(seconds/3600));
       mins = string.format("%02.f", math.floor(seconds/60 - (hours*60)));
       secs = string.format("%02.f", math.floor(seconds - hours*3600 - mins *60));
       return hours..":"..mins..":"..secs
     end
   end
`
this function add to rc.lua and "open" elapsed and duration in mpd.lua, time in mpd.lua is not useable 

maybe it is possible to have it in helpers, later  I will try it, so no need to have it in rc.lua

**Comment by McSinyx** [comment]
Thank you for providing sample output. While `os.{date,time}` doesn't work perfectly with tracks longer than 24 hours, it is still trivial to implement the formatter by one's self. Adding such function to `helpers.lua`, however, is not a good idea because the formatting of `elapsed` and `duration` should be similar (i.e. a standalone function `sec2hhmmss` should format `911` to `15:11` and `4200` to `01:10:00`, but `911/4200` should be converted to `00:15:11/01:10:00`).

I'm going to expose the time values and expand the example to show how the formatting function could be implemented.

**Comment by xhc1** [comment]
in helpers.lua I added this

      
      -- {{{ Convert seconds to clock format
       function helpers.clock(seconds)
        local seconds = tonumber(seconds)
        
     if seconds <= 0 then
       return "00:00"
     elseif
       seconds < 3600 then
       mins = string.format("%02.f", math.floor(seconds/60));
      secs = string.format("%02.f", math.floor(seconds - mins *60));
       return mins..":"..secs
      else 
       hours = string.format("%02.f", math.floor(seconds/3600));
       mins = string.format("%02.f", math.floor(seconds/60 - (hours*60)));
       secs = string.format("%02.f", math.floor(seconds - hours*3600 - mins *60));
       return hours..":"..mins..":"..secs
     end
    end   
    -- }}}

and in mpd.lua :

      
       ["{elapsed}"]  = "N/A",
       ["{duration}"]  = "N/A",
       ["{bitrate}"]  = "N/A",
      


      elseif k == "elapsed"  then mpd_state["{"..k.."}"] = v and helpers.clock(v)
      elseif k == "duration"  then mpd_state["{"..k.."}"] = v and helpers.clock(v)
      elseif k == "bitrate"  then mpd_state["{"..k.."}"] = helpers.escape(v)

and in rc.lua use 
 
```
  args["{elapsed}"]
  args["{duration}"]
  args["{bitrate}"]
```

**Comment by McSinyx** [comment]
Requested features are added, please test the PR #67 above so I may know if it is OK to merge:

```sh
cd ~/.config/awesome
git clone https://github.com/McSinyx/vicious.git
```

And update your `rc.lua` while referencing [this example](https://github.com/McSinyx/vicious#hide-mpd-widget-when-no-song-is-playing).

About your code you're proposing, thank you for your effort. Just notice that since time values are numbers, the API should return it as a number, i.e. conversion shouldn't be left for formatter. Also since Lua 5.1 (which is the minumum requirement for awesome as of this moment), the modulo operator `%` is supported so there's no need to use `a - floor(a/b)*b`.

**Comment by xhc1** [comment]
thank you by the way if there is priority to have less lines and less resources I think it could be comment out in file and user now can enable additional args very easy (same as for name and file) without creating some function for it

**Comment by Mic92** [comment]
Compared to spawning a shell and curl for every status update, this is rather lightweight calculation.
