### ISSUE TITLE
Regestering cpu wtype twice breaks it

### ISSUE THREAD

**Issue by bugdie4k** [vicious-widgets/vicious#71]
- Ubuntu 18.10
- awesome v4.2

I created two widgets like this and then used them in `s.mywibox:setup`
```lua
local cpugraph = awful.widget.graph()
vicious.register(cpugraph, vicious.widgets.cpu, "$1", 2)

local cputext = wibox.widget.textbox()
vicious.register(cputext, vicious.widgets.cpu, " CPU $1% ", 2)
```
The graph seems ok, but the text widget displays zero and sometimes peaks with 100%.
If I instead register the `cputext` first and then the `cpugraph`, then the `cputext` is the one that works fine, and the graph is broken. 

To sum it up, the widget registered first works good and the widget registered after doesn't work.

**Comment by BeniaminK** [comment]
My first question is whether pull request #52 is applied?

**Comment by Mic92** [comment]
Do you use `vicious` from `awesome-extra`? https://packages.ubuntu.com/trusty/all/awesome-extra/filelist

**Comment by bugdie4k** [comment]
> Do you use `vicious` from `awesome-extra`? https://packages.ubuntu.com/trusty/all/awesome-extra/filelist

Yes, it was from awesome-extra 2018041201. 

I purged awesome-extra, cloned vicious to /usr/share/awesome/lib/vicious (the HEAD is 6b4910e0d14f97edebd2ab43698e63b1152bfad9) and the problem persists.

**Comment by McSinyx** [comment]
I am able to reproduce the bug as well. I guess it may has something to do with low-latency querying by `cpu_linux` widgets since I can't reproduce on memory widget type.

Until this get fixed, you could try to cache the data by adding `vicious.cache(vicious.widgets.cpu)` before registering this widget type (i.e. on top of the code you post above) @bugdie4k.

**Comment by bugdie4k** [comment]
@McSinyx Thank you! Should've used caching anyway.

**Comment by McSinyx** [comment]
You're welcome. I did [some homework](https://rosettacode.org/wiki/Linux_CPU_utilization) and realised that the extreme value calculated after a infinitely small interval of time is totally expected, thus this is not at all a bug. Maybe it's worth documenting that down to avoid future confusions.
