### ISSUE TITLE
weather_all widget should require https access

### ISSUE THREAD

**Issue by yipengsun** [vicious-widgets/vicious#73]
Hi,

I just noticed that my weather widget displays `N/A`. When I try to access the weather `TXT` via `curl` directly:
```
$ curl --connect-timeout 1 -fsm 3 http://tgftp.nws.noaa.gov/data/observations/metar/decoded/KIAD.TXT

<head><body> This object may be found <a HREF="https://tgftp.nws.noaa.gov/data/observations/metar/decoded/KIAD.TXT">here</a> </body>
```

By replacing `http -> https`, the problem can be solved.

I'm using the latest `master` branch, with `awesome` 4.2.

**Comment by McSinyx** [comment]
Thank you for reporting and have a happy lunar new year!
