### ISSUE TITLE
Stop using io.popen

### ISSUE THREAD

**Issue by psychon** [vicious-widgets/vicious#74]
This is a forwarding of https://github.com/awesomeWM/awesome/issues/2697.

The short version: The volume widget uses `io.popen` to start `amixer`. For some unknown reason, `amixer` hangs(*). (Can be seen in the output of `pstree`: There is still an `amixer` process there.) As a result, all of AwesomeWM hangs.

Please use `awful.spawn.easy_async` instead.

(*) Well, or alternatively: For some weird reason, `amixer` exits, becomes a zombie (hence still shows up in `pstree`), but is not reaped via `pclose`. I'd need a backtrace for the awesome C code to see if is hung in reading `amixer`'s output or in the `pclose`, but I would expect that reading the output hangs.

CC @furgerf

**Comment by Mic92** [comment]
makes sense.

**Comment by psychon** [comment]
One more adventage of `awful.spawn` is that it also supports "arrays" instead of strings and no shell is involved. Specifically, this code:
```lua
    local cmd = "amixer -M get "
    for _, arg in ipairs(warg) do
      cmd = cmd .. " " .. helpers.shellquote(arg)
    end

    -- Get mixer control contents
    local f = io.popen(cmd)
```
can be replaced with
```lua
    local cmd = { "amixer", "-M", "get" }
    for _, arg in ipairs(warg) do
        table.insert(cmd, arg)
    end
   awful.spawn.easy_async(cmd, some_callback_function)
```
AwesomeWM's C code does not have to do word splitting to turn a string into an array, but directly uses the provided array. Thus, spaces and quotation marks are no longer a problem (well and even better: things like `$(rm -rf /)` do not cause problems (unless you happen to sent this through a shell, e.g. `{"sh","-c","echo $(rm -rf /)"}`)).

**Comment by McSinyx** [comment]
IMHO the solution might need to be more complex than simply replacing `io.popen` with Awesome `spawn.*`, since Vicious can currently be used as a standalone library we better not break backward compatibility. I'm thinking about creating a custom wrapper in `helpers` that fallbacks to `io.popen` in case Awesome API is not exposed.

Slightly related to this, all IO-intensive (heavy grepping or fetching from the Internet) widget types should make use of Awesome asynchronous when possible.

**Comment by mutlusun** [comment]
Do we have any information about our users? Is there anyone who uses vicious outside of awesome? I wouldn't be sure that there is someone. Maybe we can assume that the awesome API is available.

However, if we don't have more information about the use cases of vicious, I would stick to a cautious way and don't assume that the awesome API is available.

**Comment by Mic92** [comment]
I don't think there are many.

**Comment by McSinyx** [comment]
@psychon: Aside from blocking, is there any other reason not to use `io.popen`? Running the updater in a native Lua coroutine might save the effort of refactoring, whilst keeping backward-compatibility for standalone library.

**Comment by psychon** [comment]
Uhm...  what do you mean with "native Lua coroutine" exactly? The following still blocks for two seconds:
```
$ time lua -e '(coroutine.wrap(function() io.popen("sleep 2"):read("*a") end))()' 
lua -e '(coroutine.wrap(function() io.popen("sleep 2"):read("*a") end))()'  0,01s user 0,00s system 0% cpu 2,007 total
```
Right now I cannot think of any other major reasons not to use `io.popen`.

Minor reasons:
- With `awesome.spawn`, we also make sure that the new process gets its own session (by calling `setsid()` in the child process). This was added because some software just kills its whole session when exiting and thus it also killed AwesomeWM.
- `popen` always starts a shell which is basically never needed. With `awesome.spawn`, you can start the shell only when you actually want it.
- Relative to the previous point: `spawn` simplifies quoting since one can just directly spawn `{ "program", "argument with spaces", "argument with spaces and 'weird\" $characters" }` instead of `"program \\\"argument with spaces\\\" \\\"argument with spaces and 'weird\\\\\" \\$characters"` (no idea if I go the quoting right, but that's exactly my point)

**Comment by McSinyx** [comment]
I was dumb to assume that coroutine in Lua would be similar to that in Python, i.e. running concurrently with the main thread. Thank you so much for providing extra info, now I think the best solution might be just create a fake API for `awful.spawn` to use it when Awesome is not available.

**Comment by McSinyx** [comment]
First of all, I'm so sorry for the 2-month delay: this semester was kinda rough for me so I decided to step back for a while and focus on studying.

I have just [draft a pseudo API](830f72346e54909b10550f1cc4478c80db90698f) to fallback to when `awful.spawn` is not available and really hope to get some an opinion from an Awesome maintainer (either @psychon, @actionless or @Elv13 who together wrote the library); and an advice from @Mic92 to use `helpers.shellquote` correctly, especiall when `cmd` is a table, i.e. whether if it is safe to blindly quote any command passed to `io.popen`.
