### ISSUE TITLE
Deprecate the use of io.popen in widget types

### ISSUE THREAD

**Issue by McSinyx** [vicious-widgets/vicious#82]
This is a continuation of #74. TL;DR `io.popen` may hangs Awesome on IO-intensive process, `awful.spawn.{easy_async,with_line_callback}` are better, use them instead.

Since #74 was open with a specific context/linked with a specific bug, and I need a tracker for current progress of refactoring, this issue is opened with a list of all files currently using `io.popen`:

- [x] ~~spawn.lua~~ *this is the wrapper to fallback to `io.popen` when `awful.spawn` is not availble*
- [x] helpers.lua
- [x] widgets/bat_freebsd.lua
- [x] widgets/mem_freebsd.lua
- [x] widgets/bat_openbsd.lua
- [x] widgets/hwmontemp_linux.lua
- [x] widgets/mdir_all.lua
- [x] widgets/os_all.lua
- [x] widgets/net_freebsd.lua
- [x] widgets/wifiiw_linux.lua
- [x] widgets/wifi_linux.lua
- [x] widgets/mpd_all.lua
- [x] widgets/hddtemp_linux.lua
- [x] widgets/gmail_all.lua
- [x] widgets/fs_all.lua
- [x] widgets/volume_freebsd.lua
- [x] widgets/volume_linux.lua
- [ ] contrib/ossvol_linux.lua
- [ ] contrib/openweather_all.lua
- [ ] contrib/countfiles_all.lua
- [ ] contrib/pulse_all.lua
- [ ] contrib/mpc_all.lua
- [ ] contrib/buildbot_all.lua
- [ ] contrib/nvinf_all.lua
- [x] contrib/cmus_all.lua
- [ ] contrib/sensors_linux.lua
- [ ] contrib/rss_all.lua
- [ ] contrib/wpa_all.lua
- [ ] contrib/netcfg.lua
- [ ] contrib/nvsmi_all.lua

Since there are many widget types I cannot test, I will push changes to a new branch `async` and tick the completed ones.

**Comment by mutlusun** [comment]
Hello,
I switched now the FreeBSD widgets to `spawn`. I hope, it was okay that I directly pushed to this branch without a PR. Don't hesitate to write if there is something to improve.

**Comment by McSinyx** [comment]
Thank you, all the changes look great to me :tada: What I wonder now is that if we should rebase them now and how we can do it. I have no experience working with branches and most of the times I messed up the tree so badly that eventually I had to delete the whole and create a new one :stuck_out_tongue:

**Comment by mutlusun** [comment]
If you like to, I will merge the branches into master. But I think we should wait for the other widgets to be merged to spawn.async, shouldn't we?

I'm not that experienced with git, too. ;) However, most of the time, after a lot of searching on the internet it is doing what I want ;) Actually, I think hg is most of the time easier to use ;)

**Comment by McSinyx** [comment]
> I think we should wait for the other widgets to be merged to spawn.async

Then we'll stick to that plan. Rebasing is simple, but when there are conflicts we'll need a merge commit, then pull it back to original branch, back-and-forth like that makes the log kinda poluted to me. Also we'll have more time to test before changes are pushed to master. I've never tried hg though.

**Comment by mutlusun** [comment]
Today I noticed that I totally forgot to check `helpers.lua` for use of `io.popen`. Indeed, I used `io.popen` to read sysctl tables.

Do we have a preferred approach to remove this call? Do we want to use an async call in `helpers.lua` or do we wrap `helpers.sysctl()` in an async call in a widget?

**Comment by McSinyx** [comment]
> do we wrap helpers.sysctl() in an async call in a widget?

Is it possible to do this? IMHO this would produce the clearest codebase, but after the discussion in #74 I came to the conclusion that it could not be implemented. Fix me if I'm wrong, otherwise I think we'll need to refactor `helpers.sysctl` into a handler that takes a function that take the sysctl table as an argument.

BTW `os_all` also uses `io.popen` exclusively for FreeBSD. While `uname`, like `sysctl`, is not supposed to block, at least by current implementations, I believe it's still better to play safe and be future-proof. As it'd be ugly to mix async and synchronous routines together, I suggest we should split the widget types into GNU/Linux and FreeBSD like some other ones.

**Comment by mutlusun** [comment]
Hello,
I think, I have now moved all FreeBSD related widgets to async. Please have a look at the commits and tell me, if I have missed something.

Best

**Comment by McSinyx** [comment]
Sorry, I've just got back from a two-week military training (1 to 14 august). I'll try to double check the code a quickly as possible. Please nitpick my code as well.

Cheers.
