### ISSUE TITLE
mail_widget always display 0 even though I have new emails

### ISSUE THREAD

**Issue by yipengsun** [vicious-widgets/vicious#96]
Hi,

Recently I noticed that the `mail_widget` would always display 0, even though I'm still receiving new emails. 

My mailboxes use `maildir` format.

Here's my widget config:
```lua
mail_widget = wibox.widget.textbox()
vicious.register(
    mail_widget, vicious.widgets.mdir,
    ('<span color="%s">Mail: </span><span color="%s">$1</span>'):format(
        beautiful.fg_normal, beautiful.fg_focus),
    5, { home_path .. "/mail/" })
```

System info:
* `vicious`: latest `master`
* `awesome`: 4.3
* `lua`: 5.3.5
* OS: Arch linux

Edit: reformat the sample config to display in one screen.

**Comment by McSinyx** [comment]
This is probably my fault: 7ae6a84b52ee990ce708a8afbf3f35be05aa292d.  As stated in the commit message, I don't have maildir set up to truly test the implementation.  Could you please give us a sample directory tree to examine this a bit further?  Thank you very much and have a great weekend!

**Comment by yipengsun** [comment]
Sure. In the example above, all my mailboxes are in `$HOME/mail`, now let's say we have a mailbox called `test`, the directory tree would look like this:
```
mail
└── test
    ├── cur
    ├── new
    └── tmp
```

All the new emails will be stored in `new`, once they are read, they will be moved to `cur`.

**Comment by yipengsun** [comment]
So it should just check number of files in `new` for all mailboxes, preferable ignoring dotfiles (sometimes email client/filesystem may create a dotfile, but that is not really a new email).

**Comment by McSinyx** [comment]
> they will be moved to `cur`

Will the filenames be kept?  I wonder why it was `.*/cur/.*2,[^S]*$` for `cur` but just `.*/new/.*` for `new`.  Additionally, I believe the fault was in the regex: it should be something like `.*/cur/.*:2,.*$`, or more strictly `.*/cur/\S*:2,\S*$`.  I have no idea how it was `[^S]*` in the first place, e.g. `STln` is totally a valid flag.

**Comment by yipengsun** [comment]
I just checked one of my maildirs with new emails, and the filename will **not** be kept. For example:

| status | subdir | filename |
|---|---|---|
| unread | `new` | `1575677705.6050_2.localhost` |
| read | `cur` | `1575677705.6050_2.localhost:2,S` |

**Comment by yipengsun** [comment]
I tried the latest commit, and it still doesn't work.

**Comment by McSinyx** [comment]
By 3bd7b59b2c8f999f39600ab640856342f6436d7c, it should be working now.  It was the semicolon that led to no output.

**Comment by yipengsun** [comment]
Indeed! Thank you very much.

**Comment by McSinyx** [comment]
That's great!  I'm closing this now, thank you for reporting the bug!
